comment:
  content_length: 14400
user:
  name_length: 50
  email_length: 255
  pass_minimum: 1
  avatar_size: 50
  per_page: 10
micropost:
  title_length:  144
  content_length:  1440000
  picture_size: 5
